name: Release Plugin

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Git Cliff
        run: cargo install git-cliff

      - name: Bump version and update CHANGELOG
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          VERSION=$(git-cliff --bumped-version)
          git-cliff --bump > CHANGELOG.md
          git add CHANGELOG.md
          jq --arg version "$VERSION" '.version = $version' Assets/Osopags/package.json > tmp.$$.json && mv tmp.$$.json Assets/Osopags/package.json
          git add Assets/Osopags/package.json
          git commit -m "chore: bump version to v$VERSION"
          git pull --rebase origin main
          git push origin main

      - name: Create a new tag
        run: |
          VERSION=$(git-cliff --bumped-version)
          git tag $VERSION
          git push origin $VERSION

      - name: Push to osopags-plugin-unity
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Clone the target repository using the PAT
          git clone https://$PAT_TOKEN@github.com/k00mu/osopags-plugin-unity.git plugin-repo
          cd plugin-repo

          # Copy the relevant files
          rsync -av --delete --exclude '.git' ../Assets/Osopags/ .

          # Commit and push changes with version in the commit message
          VERSION=$(git-cliff --bumped-version)
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "v$VERSION"
          git push origin main
