name: Release Plugin

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: Install Git Cliff
        run: cargo install git-cliff

      - name: Check bump version
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          echo 'Creating cliff.toml configuration'
          cat > cliff.toml << 'EOL'
          # Paste the entire cliff.toml content here
          EOL
          NEW_VERSION_TAG=$(git-cliff --bumped-version)
          jq --arg version "$NEW_VERSION_TAG" '.version = $version' Assets/Osopags/package.json > tmp.$$.json && mv tmp.$$.json Assets/Osopags/package.json
          if [ -n "$(git diff --name-only HEAD -- ./Assets/Osopags/package.json)" ]; then
            echo "Bumping version"
            git-cliff --bump > CHANGELOG.md
            git add CHANGELOG.md Assets/Osopags/package.json cliff.toml
            git commit -m "chore: bump version to v$NEW_VERSION_TAG [skip ci]"
            git pull --rebase origin main
            git push https://$PAT_TOKEN@github.com/k00mu/osopags-sample-unity.git main
            git tag $NEW_VERSION_TAG
            git push https://$PAT_TOKEN@github.com/k00mu/osopags-sample-unity.git $NEW_VERSION_TAG
          else
            echo "No version bump required"
          fi

      - name: Push to osopags-plugin-unity
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          VERSION=$(git-cliff --bumped-version)
          LATEST_COMMIT_HASH=$(git rev-parse --short HEAD)
          git clone https://$PAT_TOKEN@github.com/k00mu/osopags-plugin-unity.git plugin-repo
          cd plugin-repo

          # Copy the relevant files
          rsync -av --delete --exclude '.git' ../Assets/Osopags/ .

          # Commit and push changes with version in the commit message
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "update from https://github.com/k00mu/osopags-sample-unity/commit/$LATEST_COMMIT_HASH"
          git push https://$PAT_TOKEN@github.com/k00mu/osopags-plugin-unity.git main
          if [ -n "$(git diff --name-only HEAD -- ../Assets/Osopags/package.json)" ]; then
            git tag $VERSION
            git push https://$PAT_TOKEN@github.com/k00mu/osopags-plugin-unity.git $VERSION
          fi
