name: Release Plugin

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Git Cliff
      run: |
        sudo apt-get update
        sudo apt-get install -y git-cliff

    - name: Bump version and update CHANGELOG
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git-cliff --bumped-version
        git-cliff --bump > CHANGELOG.md
        git add CHANGELOG.md
        git commit -m "chore: update CHANGELOG.md"
        git push origin main

    - name: Create a new tag
      run: |
        VERSION=$(git-cliff --bumped-version)
        git tag $VERSION
        git push origin $VERSION

    - name: Push to osopags-plugin-unity
      env:
        REPO_URL: https://github.com/k00mu/osopags-plugin-unity.git
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Clone the target repository
        git clone $REPO_URL plugin-repo
        cd plugin-repo

        # Copy the relevant files
        rsync -av --delete ../Assets/Osopags/ ./Assets/Osopags/

        # Commit and push changes with version in the commit message
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Update to version $VERSION"
        git push origin main